<a href="https://colab.research.google.com/github/SimonovBlonsky/DL_Learn/blob/main/torch_tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import numpy as np

In [17]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [18]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [19]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [21]:
# multipy
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [22]:
# div
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [23]:
# reminder
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [24]:
# exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [25]:
# Reassignment
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [26]:
tensor_a

tensor([ 6,  8, 10, 12])