<a href="https://colab.research.google.com/github/SimonovBlonsky/DL_Learn/blob/main/torch_test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

## **NUMPY ARRAYS**

In [5]:
np1 = np.random.rand(3, 4)
np1

array([[0.20362287, 0.56347456, 0.18926621, 0.33724203],
       [0.09999286, 0.1918487 , 0.80786032, 0.91789923],
       [0.12241644, 0.59577307, 0.38541584, 0.517371  ]])

In [6]:
np1.dtype

dtype('float64')

## **TENSORS**

In [7]:
tensor_2d=torch.randn(3, 4)
tensor_2d

tensor([[ 0.6654,  1.0565,  0.4086,  0.4673],
        [ 0.1732,  1.7272,  1.0560, -1.2273],
        [ 1.1938, -0.9250, -1.2221, -1.0116]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])